name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
jobs:
  runs-on: ubuntu-latest
  build:
    name: Build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build
        run: npm ci && npm run build
        env:
          VITE_SUPABASE_URL: ${{secrets.SUPABASE_URL}}
          VITE_SUPABASE_ANON_KEY: ${{secrets.SUPABASE_ANON_KEY}}

  deploy:
    name: Deploy
    needs: build
    steps:
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_REACT_JS_STUDY_RECORD }}
          channelId: live
          projectId: react-js-study-record
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
